- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copying the roboshop configuration
  ansible.builtin.copy:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: clean old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: create nginx prometheus exporter directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: download nginx prometheus exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes
