- name: load logstash
  ansible.builtin.import_tasks: logstash.yml
  when: elk_component == "logstash"

- name: load file beat
  ansible.builtin.import_tasks: filebeat.yml
  when: elk_component == "filebeat"