

- name: Add the user
  ansible.builtin.user:
    name: roboshop

- name: remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: download and xtract to a file
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download and extract application content from Nexus
  ansible.builtin.unarchive:
    src: http://{{username}}:{{password}}@172.31.24.24:8081/repository/{{component}}/{{component}}-{{appVersion}}.zip
    dest: /app
    remote_src: yes
  vars:
    username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.username', region='us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.password', region='us-east-1') }}"
    appVersion: "{{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.appVersion', region='us-east-1') }}"