#- name: nodejs repos
#  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_18.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app preq
  ansible.builtin.import_tasks: app-preq.yml



- name: download dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: schema setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined


- name: setup systemd.yml service file
  ansible.builtin.import_tasks: systemd-setup.yml